#!/bin/bash

red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)
bold=$(tput bold)

shopt -s nullglob

usage () {
	printf '\nThis script will install available dotfiles into your home folder.\n'
	printf 'Available distros are:\n\n'
	if [[ ! -d dotfiles ]]; then
		printf '\tNo dotfiles folder found.\n\n'
	elif pushd dotfiles &>/dev/null; then
		distros=( * )
		if (( ${#distros[@]} )); then
			printf '\t* %s\n' "${distros[@]}"
		else
			printf '\tNo distributions found.\n'
		fi
		popd &>/dev/null || exit
	fi
	printf '\nListed *_root folders are intended for /root folder.\n'
	printf 'so they must be "stowed" by the root user, %s%sbut you\n' "$red" "$bold"
	printf 'will have to clone the whole repo in /root folder\n'
	printf 'and run tis script from there.%s\n\n' "$reset"
	printf '	%s%sUsage: %s [-D] <distro>%s\n' "$bold" "$green" "$(basename "$0")" "$reset"
	exit "$1"
}

if [[ $# != [12] ]]; then
	usage 1 >&2
elif [[
	$EUID == 0 && $1 == ?*_root ||
	$EUID != 0 && $1 != ?*_root ||
	$PWD != "$HOME"?(/*) ]]; 
then
		usage 2 >&2
elif [[ $1 == -h ]]
then
	usage 0
fi

printf "\n%sRunning: stow -v -t ~/ -d dotfiles/ %s %s%s\n" "$red" "$@" "$reset"
stow -v -t "$HOME" -d dotfiles/ "$@"
printf "%sFinished%s\n" "$green" "$reset"
