#!/usr/bin/env bash

script_parent=$(readlink -f "${BASH_SOURCE%/*}"/.)

#echo "$script_parent/ejemplo"
printf '%s\n%s\n' "Current \$HOSTNAME found:" "$HOSTNAME"

# Terminate already running bar instances
killall -q polybar
killall -q megasync

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

#export HOSTNAME=$HOST

case $HOSTNAME in
  (GibyArch) printf '\n%s\n' "Loading polybar for Desktop PC"
             polybar -c "$script_parent"/desktop.config main &
             polybar -c "$script_parent"/desktop.config sysinfo &;;
  (AcerC1NP) printf '\n%s\n' "Loading polybar for Laptop"
             polybar -c "$script_parent"/laptop.config main &;;
  (*)        printf '\n%s\n' "$HOSTNAME" "not found.";;
esac


printf '\n%s\n%s\n\n' "Wallpapers and bars launched..." "Reloading megasync client..."

# Fetching wallpaper (I don't need this because I'm using i3-gnome with gnome-flashback)
#feh --bg-scale ~/MEGA/CONFS/WP/cern/cern3_WP.jpeg
#feh --bg-scale --no-fehbg --no-xinerama ~/MEGA/CONFS/WP/cern/cern3_WP.jpeg

megasync &

