#!/usr/bin/env bash

SCRIPT_PARENT=$(readlink -f "${BASH_SOURCE%/*}"/.)

#echo "$SCRIPT_PARENT/ejemplo"
printf '%s\n%s\n' "Current \$HOSTNAME found:" "$HOSTNAME"

# Terminate already running bar instances
killall -q polybar
killall -q megasync

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


case $HOSTNAME in
  (ArchSSDde) 
    printf '\n%s\n' "Loading polybar for Desktop PC"
    # sleep 5s &
    polybar -c "$SCRIPT_PARENT"/desktop.config main &
    polybar -c "$SCRIPT_PARENT"/desktop.config sysinfo &
    if [[ -n `xrandr | grep -F " connected " | awk '{print $1}' | grep  "VGA"` ]]; then
      bash desktop-both-hdmi-primary
    else
      bash desktop-hdmi-only
    fi
    ;;
  (jfthkpad) 
    printf '\n%s\n' "Loading polybar for Work PC"
    polybar -c "$SCRIPT_PARENT"/work.config main &
    polybar -c "$SCRIPT_PARENT"/work.config sysinfo &
    ;;
  (AcerC1NP) 
    printf '\n%s\n' "Loading polybar for Laptop"
    polybar -c "$SCRIPT_PARENT"/laptop.config main &
    ;;
  (*) 
    printf '\n%s\n' "$HOSTNAME" "not found."
    ;;
esac


printf '\n%s\n%s\n\n' "Wallpapers and bars launched..." "Reloading megasync client..."

# Fetching wallpaper (I don't need this because I'm using i3-gnome with gnome-flashback)
#feh --bg-scale ~/MEGA/CONFS/WP/cern/cern3_WP.jpeg
#feh --bg-scale --no-fehbg --no-xinerama ~/MEGA/CONFS/WP/cern/cern3_WP.jpeg

#megasync &

